version: "3"
services:
  app:
    container_name: vintars-digital-market
    restart: always
    image: vintars-digital-market
    build: .
    volumes:
      - ./:/home/vintars-digital-market
      - node_modules:/home/vintars-digital-market/node_modules

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 3000:80
      - 8080:8080
      - 8081:8081
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    # ports:
    #   - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

volumes:
  mongo-db:
  node_modules:
